server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3309/xiaoxiaobai-springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
#配置控制台打印sql日志
logging:
  level:
    xiaoxiaobai: debug
    xiaoxiaobai.orm.mybatis.mapper: trace


mybatis:
  #开启下划线转驼峰
  configuration:
    map-underscore-to-camel-case: true
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: xiaoxiaobai.entities    # 所有Entity别名类所在包


